<div>
                @if(Auth::user()->role=='admin')
                @include('admins.dashboard')
                @elseif(Auth::user()->role=='patient')
                @include('patients.dashboard')
                @elseif(Auth::user()->role=='doctor')
                @include('doctors.dashboard')
                @endif
 </div>